### ISSUE TITLE
Registered users unable to authenticate, user group changes to Public Guest

### ISSUE THREAD

**Issue by joshgowans** [lcdservices/CiviCRM-CiviAuthenticate#13]
Users lacking any membership at all should be assigned to the Registered role per the global User settings. This was working as intended, however within the past few upgrades, users in the Registered role receive the following error when attempting to login:

> You can't access the private section of this site.

Upon inspection, it appears that when Registered users attempt to login, their role is Changed to "Public" and "Guest". Disabling the CiviAuthenticate plugin fixes the problem.

### Before Login Attempt
![registered](https://user-images.githubusercontent.com/16521043/119334510-1ee51780-bc83-11eb-9d35-326c70b18834.png)

### After Login Attempt
![registered-change](https://user-images.githubusercontent.com/16521043/119334526-24daf880-bc83-11eb-98da-26be6567fa61.png)

**Comment by lcdservices** [comment]
I ran through some tests and couldn't reproduce the issue. This may have to do with how you've configured things. Let me explain what happens (I'll assume you're using the status based handling).

On the status tab of the plugin config it lists all statuses defined in the system and you must select which statuses to apply based on the membership status when a person logs in. The different statuses configured on that page become the "world" of statuses that the plugin considers. Any status *not* used on that page is ignored.

This is important because the system needs to know which statuses to remove as it cycles through the rules. Let's say you have the following:

- New = ACL1
- Current = ACL2
- Grace = Registered
- Expired = Public

If a user is a current member right now, they login and are given the ACL2 group -- AND any of the other three above are removed from their user account. If today is their end date, they flip to grace tomorrow, the ACL2 group is removed and Registered is added. Let's say they also had the Author group applied; that status is untouched. It's not part of the world of ACL groups configured by the plugin.

So I suspect what's happening is that one of your statuses explicitly applies the Registered group, and as a result, that group is removed from the user when they have any of the other statuses.

There are limitations to this model, for sure. It is what it is largely because of the history and evolution of this plugin (it dates back to the early days of Civi). You may be able to look at creating a dummy ACL group as a fall back so that the Registered group is not affected by the plugin behavior.

If you haven't used the Registered group in your config and are still seeing it removed, let me know and I'll try again to reproduce it.

**Comment by joshgowans** [comment]
In the settings, the "cancelled" status was set to the "registered" role. This appears to work when a member expires, i.e. they're assigned down to registered. However, for users that register for the site but do NOT create a membership it seems to cause an issue. 

Setting the "cancelled" status to something other than "registered" appears to resolve the problem for users that are registered with the site but do not have a membership, i.e. the ACL of "registered" is maintained and does not revert to "public" or "guest".

Of course, for users with a cancelled membership, they are set to a new role that is not "registered", which is fine. Thank you for the response.

**Comment by lcdservices** [comment]
Yes -- so the system is treating "registered" as a group it needs to actively assign or remove. The user with no membership logs in, the system determines there is no membership with canceled status, and so removes the "registered" status.

For the cancelled membership, I would just set the config to public. That's generally a harmless fallback. That way the "registered" status is handled outside of the plugin and unaffected by it.
